### PR TITLE
Use XCTSkip: Cleaner code

### PR DESCRIPTION
**Pull request by jayahariv**
* available from XCode 11.4; so it is compatible with latest XCode

### CODE REVIEW

**Comment by jayahariv** [comment]
Yes, its related to the PR. XCTSkip functions are throwing exception when it the condition is success(probably, uses exception throw to make it work?)

**Comment by pasin** [comment]
Can we wrap ignore exception when calling XCTSkipUnless?

**Comment by jayahariv** [comment]
that will not skip the test. instead continue and fail.

**Comment by pasin** [comment]
If that is the case, using XCTSkip could be annoyed when running tests from XCode even though the code is cleaner.

**Comment by pasin** [comment]
But it's puzzle to me that ignore exception doesn't work because it is just doing this:

```
+ (void) allowExceptionIn: (void (^)(void))block {
    ++gC4ExpectExceptions;
    block();
    --gC4ExpectExceptions;
}
```

**Comment by jayahariv** [comment]
Included ignore exception only method, without @try@catch

**Pull request merged**
