### PR TITLE
CBL-514: Add logging to try to track down P2P failures

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by pasin** [comment]
@borrrden What do you want to do with this PR?

**Comment by borrrden** [comment]
It was never my intention to merge this.  This was for a problem that only seemed to happen on the PR validation machine.  What is the status of this problem?

**Comment by pasin** [comment]
The PR validation seems to be fine.

**Comment by borrrden** [comment]
I know, I wasn't able to repro the problem.

**Pull request closed without merging**
