### PR TITLE
Fixed #1048 share schemes for building with xcodebuild command

### LINKED ISSUE #1048: Couchbase lite iOS binary has enable_bitcode' flag disabled
Found on couchbase lite: 1.2.0-76
Steps:
- Download the latest binary: http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.2/ios/
- Copy the couchbase lite framework and listener framework to todo lite frameworks directory
- Compile the project. 
ToDo lite ios: https://github.com/couchbaselabs/ToDoLite-iOS

Tried to run with ToDo lite app. When compiling with couchbase lite iOS getting this error

```

ld: '/Users/ashvinder/mobile_testing/ToDoLite-iOS/Frameworks/CouchbaseLite.framework/CouchbaseLite(CBL_Revision.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by pasin**
Share the following schemes for xcodebuild command:
- CBLJSViewCompiler
- CBL Listener Mac
- LiteServ
- LiteServ App

#1048

### CODE REVIEW

**Comment by snej** [comment]
Please give these some kind of distinctive name (a prefix?) that indicates they're used for builds. Maybe "Continuous…", like the existing "Continuous iOS" scheme.

That's to discourage anyone from using them in development, because (a) it's too easy to accidentally check in your local changes (args, diagnostics, etc.) to a shared scheme, and (b) those changes might mess up the Jenkins build.

**Comment by snej** [comment]
Oh, or as I wrote in the Jira ticket, do we really need this many schemes? Couldn't we just add an aggregate target that builds all of these, and one scheme to build that?

**Comment by pasin** [comment]
I like the idea of making an aggregate target (maybe just aggregate scheme). Base on my quick experiment, we still need different schemes for different SDK or platform otherwise XCode will complain about missing architecture. For example, for iOS/tvOS, we need:

1. Jenkins iOS build : `CBL iOS`, `CBL Listener`, and `CBLJSViewCompiler` (Actually we could make `CBL iOS` target to build CBLJSViewCompiler also.
2. Jenkins LiteServ build : `LiteServ` and `LiteServe App`
3. Documentation

Let me know what you think.

**Comment by michaelkwok** [comment]
I also commented in Jira.  It's cleaner if we can have an aggregated scheme per product (iOS, tvOS, macosx).  Not sure if it's too much to do it for 1.2.1 or we can shoot for 1.3.0 if you decide to do it.

**Comment by snej** [comment]
How about schemes `CI iOS`, `CI MacOS`, `CI tvOS`, then?

**Comment by michaelkwok** [comment]
Perfect!

**Pull request closed without merging**
