### PR TITLE
Close with ECONNRESET instead of null when the connection is reset by peer

### PR DESCRIPTION
**Pull request by pasin**
* The NSStreamEventEndEncountered event could be a result from either socket close requested by C4Socket or connection reset by peer.  For the latter case, we should call c4socket_closed() with ECONNRESET instead of null.

* When the stream is ended, check whether the C4Socket requested to close the connection or not. If the close wasn’t requested, use ECONNRESET to acknowledge the close when calling c4socket_closed().

#2173

### CODE REVIEW

**Comment by snej** [comment]
I don't think this is correct, because NSStream would have reported a real connection-reset as an error. What happened here seems to be that the remote host (SG) closed the socket (cleanly), but without sending a WebSocket close message.

CBLWebSocket shouldn't need to change what it's doing; LiteCore will recognize that the socket was closed without a close message, and treat that as an abnormal close (status 1006).

**Comment by pasin** [comment]
Does this mean that we should treat 1006 as a transient error to allow the replicator to retry?

**Comment by pasin** [comment]
In 2.1 CBLWebSocket, we use ECONNRESET for the case that the read/write steam is closed without close request from C4Socket. I have understood that it is the same case.

**Comment by pasin** [comment]
I'm closing this PR as we fixed this by adding the websocket abnormal close (1006) in the transient error list in LiteCore.

**Comment by borrrden** [comment]
Wait what?  I treat all unknown errors as 1006 in the .NET codebase, this will make all of them transient!

**Comment by snej** [comment]
What sort of unknown errors? There aren't any more specific codes for them? If it's a networking-level error, it's probably better to use one of the POSIX error codes.

**Comment by borrrden** [comment]
"Unknown errors" means exceptions that haven't been specifically mapped to an error code, usually because there is not really a master list of stuff that happens and exceptions that get thrown and I'm going off of what I have found so far happens.  If something else happens, it needs to get translated into a domain and number for LiteCore for a "default" bad value.

**Pull request closed without merging**
