### PR TITLE
Add Carthage instructions/badge to README

### PR DESCRIPTION
**Pull request by tleyden**

### CODE REVIEW

**Comment by jadsonlourenco** [comment]
Get error:
```
*** Skipped building couchbase-lite-ios due to the error:
Dependency "couchbase-lite-ios" has no shared framework schemes
```

**Comment by tleyden** [comment]
@jadsonlourenco thanks for trying this -- would you mind opening a separate issue for this?

This pr should be gated by that issue.

**Comment by tleyden** [comment]
@jadsonlourenco also can you try 'carthage update --platform ios'?

**Comment by tleyden** [comment]
See https://github.com/couchbase/couchbase-lite-ios/pull/994

**Comment by jadsonlourenco** [comment]
@tleyden Yes I saw this issue before I comment, and I try `carthage update --platform ios` but get the same error. TY!

**Comment by tleyden** [comment]
I added https://github.com/couchbase/couchbase-lite-ios/issues/1097

**Comment by tleyden** [comment]
Since #1097 is closed, this is ready for merge.

**Pull request merged**
