### PR TITLE
CBL-556: Only retry if there is any network issues 

### PR DESCRIPTION
**Pull request by jayahariv**
* Only retry if there is any network issues
* previously we were setting observer in case of all errors.

### CODE REVIEW

**Comment by jayahariv** [comment]
i will wait for the CI to  finish and merge this PR

**Comment by borrrden** [comment]
This won't help if the server side hangs up, the reachability start will just simply reconnect immediately right?

**Comment by jayahariv** [comment]
true, if the error is not a transient this will start again.

**Comment by jayahariv** [comment]
I will be creating another PR to include a fix for that.

**Comment by jayahariv** [comment]
https://github.com/couchbase/couchbase-lite-ios/pull/2592 fix for the issue

**Pull request merged**
