### PR TITLE
Remove deprecated CBL APIs

### PR DESCRIPTION
**Pull request by jayahariv**
Remove deprecated CBL APIs
* Database.setLogLevel
* Database.compact

### CODE REVIEW

**Comment by pasin** [comment]
Are these two in Priya's tracking sheet?

**Review by pasin — COMMENTED** [review]
Are these two tracked in Priya's sheet?

**Comment by jayahariv** [comment]
Updated the sheet

**Review by pasin — COMMENTED** [review]
LGTM

**Pull request merged**
