### PR TITLE
Added test for deep relationships (NSPredicate)

### PR DESCRIPTION
**Pull request by cflorion**
This new test should succeed but it doesn't.

### CODE REVIEW

**Comment by pasin** [comment]
Thanks a lot for the unit test. I will look into the issue shortly.

**Comment by zgramana** [comment]
@cflorion thanks for the PR. If you haven't already, please sign our contributor agreement.

**Comment by pasin** [comment]
Here is the link. 
https://github.com/couchbase/couchbase-lite-ios/wiki/Sign-the-contributor-license-agreement

**Comment by cflorion** [comment]
Okay. Is the Google Sign In supposed to work ?

**Comment by pasin** [comment]
Google recently dropped OpenId support so as of now, goole sign-in doesn't work. Can you use Yahoo?

**Comment by cflorion** [comment]
Done.

**Comment by pasin** [comment]
Thanks for signing. I'm working on the solution now.

**Comment by cflorion** [comment]
Great! thanks!

**Pull request closed without merging**
