### PR TITLE
NotifyChanges crash 

### PR DESCRIPTION
**Pull request by trr-amsiq**
Any way this can be tested?? #1739

### CODE REVIEW

**Comment by pasin** [comment]
Can you explain what this PR is for? I couldn't figure out the changes from looking at the PR because the PR contains a lot of indent changes (please revert those indent changes).

**Comment by trr-amsiq** [comment]
It is for issue #1739.
The changes are within  `- (void) dbChanged: (NSNotification*)n` 
The `doAsync` call is wrapping the whole function so that the `echoedChanges` array is owned by the `doAsync` block. This may prevent it from getting garbage collected.

**Comment by pasin** [comment]
Can you update the PR so I can take a look?

**Comment by trr-amsiq** [comment]
Just did. 
I've reverted all the indent changes but those are still showing up.

**Comment by pasin** [comment]
Thanks. I can see your change now. I'm not sure if the `echoedChanges` is the cause of the issue. I will try to work on this ASAP.

**Comment by tristanrichard** [comment]
We created the issue on May 1th and had over 3000 crashes of that kind since. 
Any way we can get fix for any time soon? It is a very critical issue for us!

**Comment by trr-amsiq** [comment]
We created the issue on May 1th and had over 3000 crashes of that kind since.
Any way we can get fix any time soon? It is a very critical issue for us!

**Comment by pasin** [comment]
Do you have a symbolicated crash log with all threads and the exception name? I can you either update it here or at the original issue?

**Comment by pasin** [comment]
Also what version of CBL iOS are you using?

**Comment by trr-amsiq** [comment]
It was first seen on 1.3.1 and we are now running 1.4

I'll update this comment as soon as I can reproduce it in debug

**Comment by pasin** [comment]
I understand that the issue is caused by `_changesToNotify` was released by another thread not that the `echoedChanges` was release. I'm going to close this PR. So please update the crash log reproduced with 1.4.0 binary on the original issue. I will try take a look right away once you updated the issue.

One thing that you should make sure in your application code is that you shouldn't share the database object across thread. Thanks.

**Pull request closed without merging**
