### PR TITLE
Add few optimizations

### PR DESCRIPTION
**Pull request by mastohhh**
try to send more work on background queues instead of main thread

### CODE REVIEW

**Comment by snej** [comment]
I'll let Pasin review this when he gets back. As far as thread-safety, if you're doing all the background work by calling -backgroundTellDatabase:, then you should be fine.

**Comment by mastohhh** [comment]
Ok thanks. I know Pasin manages the `CBLIncrementalStore` part of the framework, so maybe you can give me an idea on that : https://github.com/couchbase/couchbase-lite-ios/issues/793 ? Slow `CBLQueryEnumerator`, or if not slow, maybe it's called too often, so needs cache ?

**Comment by snej** [comment]
The CPU profiler in the Instruments app can help you track down why the query enumeration is slow. Usually the slow part is updating the index, which happens if the database has been changed since the view was last queried; every changed document gets run through the map function again and the old emitted rows get replaced by the new ones.

**Comment by mastohhh** [comment]
I tried to investigate and I don't think I can optimize this method.

My idea is : I saw that CoreData calls a lot that function, and maybe multiple times for the same query. In this case, I could reuse results instead of querying again.

I'll pull request you if I found something interesting. 

Thanks

**Comment by snej** [comment]
Caching results might be a good idea. You can check whether a query is still valid by saving the `CBLQueryEnumerator.sequenceNumber` after you run the query, and then later comparing that value with the `CBLDatabase.lastSequenceNumber`. If it's lower, you need to re-run the query.

**Comment by mastohhh** [comment]
I tried it ! But 2 tests are failing, so no need to pull request what I did ...

Or maybe if you want to know what not to do.

The good thing is : between half and quarter of queries can be reused.

**Comment by pasin** [comment]
@mastohhh Thanks for the PR. Is this PR fixing the performance issue when saving core data context?
Do you have performance result before and after applying the PR?

**Comment by pasin** [comment]
@mastohhh I have fixed the issue in https://github.com/couchbase/couchbase-lite-ios/commit/653ebafadc11bd3a8a2a71a4654098c692a14bf7. I'm closing the PR now. Please let me know if you have any issues.

PS: I also cache the relationship query result by checking CBLQueryEnumerator.sequenceNumber. I didn't see any unit tests failed.

**Comment by mastohhh** [comment]
Hi @snej @pasin, I'm back on CouchbaseLite project ! Really thank you for what you did.

I still have performance problems, and I'm working on it, I'll come back to you if I found something.

**Comment by mastohhh** [comment]
@pasin I think you forgot to initialize `_relationshipCache` ivar in `CBLIncrementalStore`.

Tell me if you want a PR, but I think it's not necessary just for one line.

**Comment by pasin** [comment]
That's bad. Let me do it. I would like to re-test everything.

**Comment by pasin** [comment]
@mastohhh I'm sorry for the bug. I have just fixed it. Recently we deprecated the enumerator's reset method in the master branch, and the enumerator should be reset before returning it from the cache. I have just fixed that issue as well. Please let me know if it solves your issue.

**Pull request closed without merging**
