### PR TITLE
Add CBLIS Performance UnitTests for save-fetch-inform

### PR DESCRIPTION
**Pull request by mastohhh**
Related to this issue : https://github.com/couchbase/couchbase-lite-ios/issues/938

@pasin : If you don't already did it : here are some examples of performance tests. I hope it will help.

### CODE REVIEW

**Comment by pasin** [comment]
Now I'm testing several things on my little experimental app. But this is very helpful. Thanks a lot.

**Comment by mastohhh** [comment]
This is my firsts performance tests. I didn't find where we can profile while testing. Too bad. I don't test with an Xcode server, maybe it warns when performance goes down.

**Comment by snej** [comment]
XCTest can measure performance by timing how long a block takes to run. Xcode can track that performance over time. See the XCTest documentation, or look at -[JSON_Tests test_CBJSONEncoderBenchmark] as a simple example.

**Comment by pasin** [comment]
Just read the difference b/w measureBlock and measureMetrics. They both are doing the same thing which is running the block 10 times to measure the performance. MeasureMetrics provides more fine grains when capturing with performance with startMeasuring: and stopMeasuring:.

**Comment by pasin** [comment]
I'm going to pull your changes in and modify it a little bit. Also I think it's better to disable the performance test by default as it slows down the overall unit test running.

**Comment by mastohhh** [comment]
MeasureMetrics also add ability to monitor asynchronous work, as you can see in the performanceInform test.

**Comment by mastohhh** [comment]
You can also reduce the number of objects.

I think these tests are good just to be sure of improvements we made. Not just a feeling.

**Comment by pasin** [comment]
I have just manually merged your changes and made some minor modifications.

https://github.com/couchbase/couchbase-lite-ios/pull/956

**Comment by pasin** [comment]
Anyway, thanks a lot for your contribution.

**Pull request closed without merging**
