### PR TITLE
CBL-2392: Add a small delay to make the unit test pass

### PR DESCRIPTION
**Pull request by jayahariv**
Add a small delay to make the unit test pass

### CODE REVIEW

**Comment by pasin** [comment]
Can you explain why putting 0.1 delay make the unit test pass?

**Review by pasin — COMMENTED** [review]
This seems to be a LiteCore issue that doesn't update the expiry time but I don't understand why adding 0.1 delay makes the test pass. Can you explain? Also I think it's better to disable the test until the underling issue is fix instead of adding a workaround.

**Comment by pasin** [comment]
Also there seems to be an issue with PR validation.

**Comment by jayahariv** [comment]
PR validation is failing on other unit tests. 

My understanding was 0.1 is giving enough time to save the new value. Which seems to be passing tests 5/5 times. I haven't seen the same test fail after this delay. But sure, we could wait for the LiteCore fix, and then enable, which would be the ideal fix.

**Pull request closed without merging**
