### PR TITLE
Fix awakeFromInitializer document assertion fail (#521)

### PR DESCRIPTION
**Pull request by pasin**
* Not checking the existence of the document when the model is new.
* Include API_ModelAwakeFromInitializer unit test.

#521

### CODE REVIEW

**Comment by snej** [comment]
This will fix the immediate crash, but I think it's wrong that the model doesn't have a document at the time that awakeFromInitializer is called. It should be an invariant that a model always has a document.

I think the right fix is to copy these lines from `-setDatabase:` into the init method, in the `document==nil` case:
```
        NSString* docID = [self idForNewDocumentInDatabase: db];
        self.document = docID ? [db documentWithID: docID] : [db createDocument];
```

**Comment by pasin** [comment]
That doesn't work with -initWithDocument as at the time is the document is nil, the database is also nil too. Should we create a new init method (e.g. -initWithDatabase?) for a new fresh model instead?

**Comment by snej** [comment]
Looks good, but you're going to have to merge with master and resolve some conflicts, due to my refactoring of the unit tests.

**Comment by pasin** [comment]
Rebased, fixed the conflict, and re-added the unit test for the awakeFromInitializer method. Merging now.

**Pull request merged**
