### PR TITLE
GH Actions: Xcode build for ObjC and Swift tests

### PR DESCRIPTION
**Pull request by jayahariv**
test PRs and push to master on CBL-ObjC and CBL-Swift scheme tests

### CODE REVIEW

**Comment by jayahariv** [comment]
since we are doing the Actions probably we can remove the Travis CI right?

**Comment by pasin** [comment]
Yes. Do we still need to do on Jenkins especially for EE?

**Review by pasin — APPROVED** [review]

**Comment by pasin** [comment]
Please remove travis.

**Comment by jayahariv** [comment]
Yes, we do require the Jenkins EE validation.

**Pull request merged**
